### PR TITLE
Bump minimum pandas requirement and remove workaround

### PR DESCRIPTION
**Pull request by xuhdev**
Pandas 1.2.0 has fixed the bug that we tried to workaround

---

## Checklist:

<details open>

<summary></summary>

- Does this pull request close an issue? We encourage you to open an issue first if this pull request (PR) is not a
  minor change.
  - [x] No
    - [x] The change in this pull request is minor.
  - [ ] Yes
    - Close #{issue_number}

For the following questions, only check the boxes that are applicable.

- [x] Ensure that the pull request text above the horizontal line is descriptive.
- [x] Add/update relevant tests.
- [x] Add/update relevant documents.

- Do you have triage permission of this repository?
  - [ ] No
    - You are good.
  - [x] Yes
    - Does this pull request close an issue?
      - [x] No, this pull request also acts as an issue by itself.
        - [x] Assign yourself.
        - [x] Label this pull request.
        - [x] Put a milestone.
        - [x] Put this pull request under "In Progress" or "Under Review" pipeline on ZenHub.
        - [x] Put this pull request under the appropriate epic on ZenHub.
        - [x] Put an estimate on ZenHub.
        - [x] Add dependency relationship with other issues/pull requests on ZenHub.
      - [ ] Yes, this pull request addresses an issue and does not act as an issue.
        - [ ] Connect this pull request to the underlying issue on ZenHub.
        - [ ] DON'T:
          - DON'T assign yourself or anyone else.
          - DON'T label.
          - DON'T put a milestone.
          - DON'T put this pull request under any epic on ZenHub.
          - DON'T put an estimate on ZenHub.
    - [x] When the pull request is ready, request review.
</details>

### CODE REVIEW

**Comment by xuhdev** [comment]
The failure seems relevant to https://github.com/tox-dev/tox/issues/1768

**Comment by xuhdev** [comment]
Actually this is caused by the fact that pandas has stopped support Python 3.6 since the first release this year: https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html

Should we drop Python 3.6 at this point of time? One option is that we keep the workaround in the code base and only remove them after Python 3.6 support should be dropped.

**Comment by edwardleardi** [comment]
Yeah it's probably fine to drop 3.6 since the overlap between Pandas users and potential PyDAX users would be very high. I'm good with dropping now or later, whatever you prefer.

**Comment by xuhdev** [comment]
Let's keep things as they are now; pandas 1.1.5 is still good with Python 3.6. It's safer to drop later.

**Pull request closed without merging**
