### PR TITLE
Use readthedocs to build/host docs

### PR DESCRIPTION
**Pull request by edwardleardi**
Docs currently built here: https://pydax.readthedocs.io/en/read-the-docs-hosting/index.html
Once PR is merged, will change default branch to be built from `read-the-docs-hosting` to `master` inside of the readthedocs settings

### CODE REVIEW

**Review by xuhdev — APPROVED** [review]
I think it's OK to use readthedoc for now, but likely we will move onto our IBM location by having some CD uploading the documents. (The ads aren't probably what we want to show to users for this project)

**Comment by edwardleardi** [comment]
> I think it's OK to use readthedoc for now, but likely we will move onto our IBM location by having some CD uploading the documents. (The ads aren't probably what we want to show to users for this project)

Oh ok, I just copied what Elyra did again. Makes sense

**Comment by edwardleardi** [comment]
Switched readthedocs to build the master branch, now the docs are available at: https://pydax.readthedocs.io/en/latest/ 
FYI, I also added the link in the About section of the GitHub page

**Comment by xuhdev** [comment]
> Switched readthedocs to build the master branch, now the docs are available at: https://pydax.readthedocs.io/en/latest/
> FYI, I also added the link in the About section of the GitHub page

I don't see an "About" section :smile_cat:

**Comment by edwardleardi** [comment]
To the right of the code files where the repo metadata is listed! I also added a few relevant tags, feel free to adjust. 

image

**Comment by xuhdev** [comment]
Got it, thanks, I thought you added an About section to the doc

**Pull request merged**
